# Form implementation generated from reading ui file 'questions_layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Question(object):
    def setupUi(self, Question):
        Question.setObjectName("Question")
        Question.resize(470, 365)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Question)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 451, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.questionLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.questionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.questionLabel.setObjectName("questionLabel")
        self.verticalLayout.addWidget(self.questionLabel)
        self.nextbutton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.nextbutton.setObjectName("nextbutton")
        self.verticalLayout.addWidget(self.nextbutton)

        self.retranslateUi(Question)
        QtCore.QMetaObject.connectSlotsByName(Question)

    def retranslateUi(self, Question):
        _translate = QtCore.QCoreApplication.translate
        Question.setWindowTitle(_translate("Question", "Questions"))
        self.questionLabel.setText(_translate("Question", "TextLabel"))
        self.nextbutton.setText(_translate("Question", "Next"))
